### ISSUE TITLE
Hue and Saturation support

### ISSUE THREAD

**Issue by rbdubz3** [MindrustUK/python-lightify#2]
Thanks for the useful library. Much better than making a round trip to the Osram REST API. My question is reg'd Hue as Saturation. The REST API support the ability to change hue (0-360) and saturation (0-1). 

Any plans to add calls for setting hue and saturation? Or maybe this can already be achieved via the other calls - rgb, luminance, and temperature

**Comment by MindrustUK** [comment]
I'm no longer maintaining this since I've switched to using a Philips Hue system, however Thomas over at [](https://github.com/tfriedel/python-lightify)  has taken over writing compatible and vastly improved code for Home Assistant which may do what you want.
